<?php
if(function_exists("register_field_group"))
{
	$my_theme = wp_get_theme();
	$themeName = $my_theme->get( 'Name' );
	register_field_group(array (
		'id' => 'acf_article-fields',
		'title' => __('Article Fields', $themeName),
		'fields' => array (
			array (
				'key' => 'field_56b399754c220',
				'label' => __('Full Width?', $themeName),
				'name' => 'full_width',
				'type' => 'radio',
				'choices' => array (
					'Yes' => __('Yes', $themeName),
					'No' => __('No', $themeName),
					'Global' => __('Follow the global blog setting', $themeName),
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Global',
				'instructions' => __('Select to have the post body span the full width of the page (that is, do not show the right sidebar).', $themeName),
				'message' => __('Post body spans the full page width', $themeName),
			),
			array (
				'key' => 'field_56b399754c221',
				'label' => __('Allow comments', $themeName),
				'name' => 'allow_comments',
				'type' => 'radio',
				'choices' => array (
					'Yes' => __('Yes', $themeName),
					'No' => __('No', $themeName),
					'Global' => __('Follow the global blog setting', $themeName),
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Global',
				'instructions' => __('Select to allow or disable comments for this post.', $themeName),
				'message' => '',
			),
			array (
				'key' => 'field_575097d49ecfc',
				'label' => __('Display social links to share this post?', $themeName),
				'name' => 'social_share',
				'type' => 'radio',
				'choices' => array (
					'Yes' => __('Yes', $themeName),
					'No' => __('No', $themeName),
					'Global' => __('Follow the global blog setting', $themeName),
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Global',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_574ef651c3do1',
				'label' => __('Title Size', $themeName),
				'name' => 'leadspace_title_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h1 ibm-large' => __('Larger', $themeName),
					'ibm-h1 ibm-medium' => __('Normal', $themeName),
					'ibm-h1' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h1 ibm-medium',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efbc84845e',
				'label' => __('Title Weight', $themeName),
				'name' => 'leadspace_title_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574ef123c3d98',
				'label' => __('Text Color', $themeName),
				'name' => 'text_color',
				'type' => 'select',
				'instructions' => __('View https://www.ibm.com/standards/web/patterns/text for example color options', $themeName),
				'choices' => array (
					'ibm-textcolor-default' => 'Black',
					'ibm-textcolor-white-core' => 'White',
					'ibm-textcolor-blue-30' => 'Blue 30',
					'ibm-textcolor-blue-40' => 'Blue 40',
					'ibm-textcolor-blue-50' => 'Blue 50',
					'ibm-textcolor-blue-60' => 'Blue 60',
					'ibm-textcolor-gray-30' => 'Gray 30',
					'ibm-textcolor-gray-40' => 'Gray 40',
					'ibm-textcolor-gray-50' => 'Gray 50',
					'ibm-textcolor-gray-60' => 'Gray 60',
					'ibm-textcolor-gray-80' => 'Gray 80',
					'ibm-textcolor-green-30' => 'Green 30',
					'ibm-textcolor-green-40' => 'Green 40',
					'ibm-textcolor-green-50' => 'Green 50',
					'ibm-textcolor-green-60' => 'Green 60',
					'ibm-textcolor-magenta-20' => 'Magenta 20',
					'ibm-textcolor-magenta-30' => 'Magenta 30',
					'ibm-textcolor-magenta-50' => 'Magenta 50',
					'ibm-textcolor-magenta-60' => 'Magenta 60',
					'ibm-textcolor-orange-30' => 'Orange 30',
					'ibm-textcolor-orange-40' => 'Orange 40',
					'ibm-textcolor-orange-50' => 'Orange 50',
					'ibm-textcolor-orange-60' => 'Orange 60',
					'ibm-textcolor-purple-20' => 'Purple 20',
					'ibm-textcolor-purple-30' => 'Purple 30',
					'ibm-textcolor-purple-50' => 'Purple 50',
					'ibm-textcolor-purple-60' => 'Purple 60',
					'ibm-textcolor-red-30' => 'Red 30',
					'ibm-textcolor-red-40' => 'Red 40',
					'ibm-textcolor-red-50' => 'Red 50',
					'ibm-textcolor-red-60' => 'Red 60',
					'ibm-textcolor-teal-30' => 'Teal 30',
					'ibm-textcolor-teal-40' => 'Teal 40',
					'ibm-textcolor-teal-50' => 'Teal 50',
					'ibm-textcolor-teal-60' => 'Teal 60',
					'ibm-textcolor-yellow-10' => 'Yellow 10',
					'ibm-textcolor-yellow-30' => 'Yellow 30',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56e871ff9629c',
				'label' => __('Leadspace Image', $themeName),
				'name' => 'leadspace_image',
				'type' => 'image',
				'instructions' => __('Upload the article\'s main image. Size requirements 1440 × 320', $themeName),
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_564505442f665',
				'label' => __('Card Image', $themeName),
				'name' => 'card_image',
				'type' => 'image',
				'instructions' => __('Upload the article\'s card image. Recommended size is 380 x 190', $themeName),
				'save_format' => 'object',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c38ea4140a9',
				'label' => __('Add Second Author', $themeName),
				'name' => 'guest_author',
				'type' => 'true_false',
				'message' => __('Enable', $themeName),
				'default_value' => 0,
			),
			array (
				'key' => 'field_56c38ec6140aa',
				'label' => __('Author 2 - Name', $themeName),
				'name' => 'guest_author_name',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c38ea4140a9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_570d2fc06121d',
				'label' => __('Author 2 - Website Link', $themeName),
				'name' => 'guest_author_website_link',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c38ea4140a9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c38ed4140ab',
				'label' => __('Author 2 - Image', $themeName),
				'name' => 'guest_author_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c38ea4140a9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c38ee7140ac',
				'label' => __('Author 2 - Title/Dept', $themeName),
				'name' => 'guest_author_description',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c38ea4140a9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_author',
		'title' => 'Author',
		'fields' => array (
			array (
				'key' => 'field_56cc72a8eab4d',
				'label' => __('Profile Picture', $themeName),
				'name' => 'author_icon',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'instructions' => __('Image used on author, contributors and article pages.', $themeName) . "<br/>" . __('Recommended size:', $themeName) . " 300 × 300",
				'library' => 'all',
			),
			array (
				'key' => 'field_568f47c5eeafd',
				'label' => __('Leadspace Title', $themeName),
				'name' => 'author_title_large',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574ef651c3do2',
				'label' => __('Title Size', $themeName),
				'name' => 'leadspace_title_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h1 ibm-large' => __('Larger', $themeName),
					'ibm-h1 ibm-medium' => __('Normal', $themeName),
					'ibm-h1' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h1 ibm-medium',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efbc84845f',
				'label' => __('Title Weight', $themeName),
				'name' => 'leadspace_title_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_413ef587c3de8',
				'label' => __('Text Color', $themeName),
				'name' => 'leadspace_title_color',
				'type' => 'select',
				'instructions' => __('View https://www.ibm.com/standards/web/patterns/text for example color options', $themeName),
				'choices' => array (
					'ibm-textcolor-default' => 'Black',
					'ibm-textcolor-white-core' => 'White',
					'ibm-textcolor-blue-30' => 'Blue 30',
					'ibm-textcolor-blue-40' => 'Blue 40',
					'ibm-textcolor-blue-50' => 'Blue 50',
					'ibm-textcolor-blue-60' => 'Blue 60',
					'ibm-textcolor-gray-30' => 'Gray 30',
					'ibm-textcolor-gray-40' => 'Gray 40',
					'ibm-textcolor-gray-50' => 'Gray 50',
					'ibm-textcolor-gray-60' => 'Gray 60',
					'ibm-textcolor-gray-80' => 'Gray 80',
					'ibm-textcolor-green-30' => 'Green 30',
					'ibm-textcolor-green-40' => 'Green 40',
					'ibm-textcolor-green-50' => 'Green 50',
					'ibm-textcolor-green-60' => 'Green 60',
					'ibm-textcolor-magenta-20' => 'Magenta 20',
					'ibm-textcolor-magenta-30' => 'Magenta 30',
					'ibm-textcolor-magenta-50' => 'Magenta 50',
					'ibm-textcolor-magenta-60' => 'Magenta 60',
					'ibm-textcolor-orange-30' => 'Orange 30',
					'ibm-textcolor-orange-40' => 'Orange 40',
					'ibm-textcolor-orange-50' => 'Orange 50',
					'ibm-textcolor-orange-60' => 'Orange 60',
					'ibm-textcolor-purple-20' => 'Purple 20',
					'ibm-textcolor-purple-30' => 'Purple 30',
					'ibm-textcolor-purple-50' => 'Purple 50',
					'ibm-textcolor-purple-60' => 'Purple 60',
					'ibm-textcolor-red-30' => 'Red 30',
					'ibm-textcolor-red-40' => 'Red 40',
					'ibm-textcolor-red-50' => 'Red 50',
					'ibm-textcolor-red-60' => 'Red 60',
					'ibm-textcolor-teal-30' => 'Teal 30',
					'ibm-textcolor-teal-40' => 'Teal 40',
					'ibm-textcolor-teal-50' => 'Teal 50',
					'ibm-textcolor-teal-60' => 'Teal 60',
					'ibm-textcolor-yellow-10' => 'Yellow 10',
					'ibm-textcolor-yellow-30' => 'Yellow 30',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_568f4778eeafc',
				'label' => __('Background Image', $themeName),
				'name' => 'background_image',
				'type' => 'image',
				'instructions' => __('leadspace image. Recommended size is 1440 × 320', $themeName),
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5695250862a32',
				'label' => __('Twitter link', $themeName),
				'name' => 'ibm_author_social_twitter',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5695253262a33',
				'label' => __('LinkedIn Link', $themeName),
				'name' => 'ibm_author_social_linkedin',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5695253f62a34',
				'label' => __('Facebook link', $themeName),
				'name' => 'ibm_author_social_facebook',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5696a7ef9e29b',
				'label' => __('Job Title', $themeName),
				'name' => 'job_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_565e70b266d65',
				'label' => __('Post listing style', $themeName),
				'name' => 'post_listing_style',
				'instructions' => '',
				'type' => 'radio',
				'message' => '',
				'choices' => array(
					'grid' => __('Grid', $themeName),
					'stack' => __('Stack', $themeName),
					'global' => __('Follow global settings', $themeName),
				),
				'default_value' => 'global',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'all',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_categories',
		'title' => 'Categories',
		'fields' => array (
			array (
				'key' => 'field_565e70b266d63',
				'label' => __('Main Image', $themeName),
				'name' => 'main_image',
				'type' => 'image',
				'instructions' => __('Leadspace Image Dimensions: 1440 × 320', $themeName),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_565e70b266d65',
				'label' => __('Post listing style', $themeName),
				'name' => 'post_listing_style',
				'instructions' => '',
				'type' => 'radio',
				'message' => '',
				'choices' => array(
					'grid' => __('Grid', $themeName),
					'stack' => __('Stack', $themeName),
					'global' => __('Follow global settings', $themeName),
				),
				'default_value' => 'global',
			),
			array (
				'key' => 'field_574ef651c3do3',
				'label' => __('Title Size', $themeName),
				'name' => __('leadspace_title_size', $themeName),
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h1 ibm-large' => __('Larger', $themeName),
					'ibm-h1 ibm-medium' => __('Normal', $themeName),
					'ibm-h1' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h1 ibm-medium',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efbc84845g',
				'label' => __('Title Weight', $themeName),
				'name' => 'leadspace_title_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_084efe56888f9',
				'label' => __('Description Size', $themeName),
				'name' => 'leadspace_description_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h3' => __('Larger', $themeName),
					'ibm-h4' => __('Normal', $themeName),
					'\'\'' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h4',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_084efe6d888fa',
				'label' => __('Description Weight', $themeName),
				'name' => 'leadspace_description_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574ef587c3094',
				'label' => __('Text Color', $themeName),
				'name' => 'text_color',
				'type' => 'select',
				'instructions' => __('View https://www.ibm.com/standards/web/patterns/text for example color options', $themeName),
				'choices' => array (
					'ibm-textcolor-default' => 'Black',
					'ibm-textcolor-white-core' => 'White',
					'ibm-textcolor-blue-30' => 'Blue 30',
					'ibm-textcolor-blue-40' => 'Blue 40',
					'ibm-textcolor-blue-50' => 'Blue 50',
					'ibm-textcolor-blue-60' => 'Blue 60',
					'ibm-textcolor-gray-30' => 'Gray 30',
					'ibm-textcolor-gray-40' => 'Gray 40',
					'ibm-textcolor-gray-50' => 'Gray 50',
					'ibm-textcolor-gray-60' => 'Gray 60',
					'ibm-textcolor-gray-80' => 'Gray 80',
					'ibm-textcolor-green-30' => 'Green 30',
					'ibm-textcolor-green-40' => 'Green 40',
					'ibm-textcolor-green-50' => 'Green 50',
					'ibm-textcolor-green-60' => 'Green 60',
					'ibm-textcolor-magenta-20' => 'Magenta 20',
					'ibm-textcolor-magenta-30' => 'Magenta 30',
					'ibm-textcolor-magenta-50' => 'Magenta 50',
					'ibm-textcolor-magenta-60' => 'Magenta 60',
					'ibm-textcolor-orange-30' => 'Orange 30',
					'ibm-textcolor-orange-40' => 'Orange 40',
					'ibm-textcolor-orange-50' => 'Orange 50',
					'ibm-textcolor-orange-60' => 'Orange 60',
					'ibm-textcolor-purple-20' => 'Purple 20',
					'ibm-textcolor-purple-30' => 'Purple 30',
					'ibm-textcolor-purple-50' => 'Purple 50',
					'ibm-textcolor-purple-60' => 'Purple 60',
					'ibm-textcolor-red-30' => 'Red 30',
					'ibm-textcolor-red-40' => 'Red 40',
					'ibm-textcolor-red-50' => 'Red 50',
					'ibm-textcolor-red-60' => 'Red 60',
					'ibm-textcolor-teal-30' => 'Teal 30',
					'ibm-textcolor-teal-40' => 'Teal 40',
					'ibm-textcolor-teal-50' => 'Teal 50',
					'ibm-textcolor-teal-60' => 'Teal 60',
					'ibm-textcolor-yellow-10' => 'Yellow 10',
					'ibm-textcolor-yellow-30' => 'Yellow 30',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_categories-page',
		'title' => __('Categories Page', $themeName),
		'fields' => array (
			array (
				'key' => 'field_57605d6a1b6b8',
				'label' => __('Columns', $themeName),
				'name' => 'columns',
				'type' => 'radio',
				'instructions' => __('Choose 1/2/3 columns', $themeName),
				'choices' => array (
					'1-1' => 1,
					'2-1' => 2,
					'6-2' => 3,
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 2,
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '31936',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer-band',
		'title' => __('Footer Band', $themeName),
		'fields' => array (
			array (
				'key' => 'field_56e872317bdd5',
				'label' => __('Footer Band', $themeName),
				'name' => 'footer_band',
				'type' => 'true_false',
				'instructions' => '',
				'message' => __('Enable Footer Band', $themeName),
				'default_value' => 1,
			),
			array (
				'key' => 'field_56a938dcc236e',
				'label' => __('Title', $themeName),
				'name' => 'title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a938e7c236f',
				'label' => __('description', $themeName),
				'name' => 'description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56a93971c2376',
				'label' => __('Background Image', $themeName),
				'name' => 'background_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56aa3de1ab652',
				'label' => __('Text color', $themeName),
				'name' => 'dark_background',
				'type' => 'radio',
				'instructions' => __('Controls the color of the text on the Footer Band Background Image.', $themeName),
				'message' => '',
				'choices' => array(
					0 => __('Black text (good for light background images)', $themeName),
					1 => __('White text (good for dark background images)', $themeName)
				),
				'default_value' => 0,
			),
			array (
				'key' => 'field_56a93991c2377',
				'label' => __('Parallax', $themeName),
				'name' => 'parallax_option',
				'type' => 'true_false',
				'instructions' => __('Provides a visually interesting effect as the page scrolls', $themeName),
				'message' => __('Turn Parallax on', $themeName),
				'default_value' => 0,
			),
			array (
				'key' => 'field_56a93a7f3b571',
				'label' => __('Number of CTAs', $themeName),
				'name' => 'cta_num',
				'type' => 'select',
				'choices' => array (
					'1_cta' => 1,
					'2_cta' => 2,
					'3_cta' => 3,
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56a938fbc2370',
				'label' => __('CTA 1 Text', $themeName),
				'name' => 'cta_1_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a93916c2371',
				'label' => __('CTA 1 url', $themeName),
				'name' => 'cta_1_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a93942c2372',
				'label' => __('CTA 2 text', $themeName),
				'name' => 'cta_2_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a93952c2373',
				'label' => __('CTA 2 url', $themeName),
				'name' => 'cta_2_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a9395bc2374',
				'label' => __('CTA 3 text', $themeName),
				'name' => 'cta_3_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a93963c2375',
				'label' => __('CTA 3 url', $themeName),
				'name' => 'cta_3_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post',
					'operator' => '==',
					'value' => '31791',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer-social-links',
		'title' => __('Footer Social Links', $themeName),
		'fields' => array (
			array (
				'key' => 'field_570fce6b15786',
				'label' => __('Social Icons', $themeName),
				'name' => 'social_icons',
				'type' => 'true_false',
				'instructions' => __('Check box to enable the social links band', $themeName),
				'message' => __('Enable Social Links Band', $themeName),
				'default_value' => 1,
			),
			array (
				'key' => 'field_56a9237516f89',
				'label' => __('Facebook Link', $themeName),
				'name' => 'facebook_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a9237516e20',
				'label' => __('Twitter Link', $themeName),
				'name' => 'twitter_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a9237e16e21',
				'label' => __('Linkedin Link', $themeName),
				'name' => 'linkedin_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56aa7602e8a90',
				'label' => __('Youtube Link', $themeName),
				'name' => 'youtube_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56bccab5808a1',
				'label' => __('googleplus link', $themeName),
				'name' => 'googleplus_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56a9237516f90',
				'label' => __('RSS Link', $themeName),
				'name' => 'rss_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post',
					'operator' => '==',
					'value' => '31787',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-leadspace',
		'title' => __('Home Leadspace', $themeName),
		'fields' => array (
			array (
				'key' => 'field_565e71493fa2e',
				'label' => __('Main Title', $themeName),
				'name' => 'main_title',
				'type' => 'text',
				'instructions' => __('Please put the name of your blog in this space use sentence case structure. ie "The blog"', $themeName),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574ef651c3de9',
				'label' => __('Title Size', $themeName),
				'name' => 'leadspace_title_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h1 ibm-large' => __('Larger', $themeName),
					'ibm-h1 ibm-medium' => __('Normal', $themeName),
					'ibm-h1' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h1 ibm-medium',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efbc84877e',
				'label' => __('Title Weight', $themeName),
				'name' => 'leadspace_title_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_565e717d3fa2f',
				'label' => __('Sub Title', $themeName),
				'name' => 'sub_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574ef712c3dea',
				'label' => __('Subtitle Size', $themeName),
				'name' => 'leadspace_subtitle_size',
				'type' => 'select',
				'instructions' => 'Select size',
				'choices' => array (
					'ibm-h2' => __('Larger', $themeName),
					'ibm-h3' => __('Normal', $themeName),
					'ibm-h4' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h3',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efc684877f',
				'label' => __('Subtitle Weight', $themeName),
				'name' => 'leadspace_subtitle_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_565e71923fa30',
				'label' => __('Description', $themeName),
				'name' => 'credit',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
			),
			array (
				'key' => 'field_574efe56888f9',
				'label' => __('Description Size', $themeName),
				'name' => 'leadspace_description_size',
				'type' => 'select',
				'instructions' => 'Select size',
				'choices' => array (
					'ibm-h3' => __('Larger', $themeName),
					'ibm-h4' => __('Normal', $themeName),
					'\'\'' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h4',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efe6d888fa',
				'label' => __('Description Weight', $themeName),
				'name' => 'leadspace_description_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574ef587c3de8',
				'label' => __('Text Color', $themeName),
				'name' => 'text_color',
				'type' => 'select',
				'instructions' => __('View https://www.ibm.com/standards/web/patterns/text for example color options', $themeName),
				'choices' => array (
					'ibm-textcolor-default' => 'Black',
					'ibm-textcolor-white-core' => 'White',
					'ibm-textcolor-blue-30' => 'Blue 30',
					'ibm-textcolor-blue-40' => 'Blue 40',
					'ibm-textcolor-blue-50' => 'Blue 50',
					'ibm-textcolor-blue-60' => 'Blue 60',
					'ibm-textcolor-gray-30' => 'Gray 30',
					'ibm-textcolor-gray-40' => 'Gray 40',
					'ibm-textcolor-gray-50' => 'Gray 50',
					'ibm-textcolor-gray-60' => 'Gray 60',
					'ibm-textcolor-gray-80' => 'Gray 80',
					'ibm-textcolor-green-30' => 'Green 30',
					'ibm-textcolor-green-40' => 'Green 40',
					'ibm-textcolor-green-50' => 'Green 50',
					'ibm-textcolor-green-60' => 'Green 60',
					'ibm-textcolor-magenta-20' => 'Magenta 20',
					'ibm-textcolor-magenta-30' => 'Magenta 30',
					'ibm-textcolor-magenta-50' => 'Magenta 50',
					'ibm-textcolor-magenta-60' => 'Magenta 60',
					'ibm-textcolor-orange-30' => 'Orange 30',
					'ibm-textcolor-orange-40' => 'Orange 40',
					'ibm-textcolor-orange-50' => 'Orange 50',
					'ibm-textcolor-orange-60' => 'Orange 60',
					'ibm-textcolor-purple-20' => 'Purple 20',
					'ibm-textcolor-purple-30' => 'Purple 30',
					'ibm-textcolor-purple-50' => 'Purple 50',
					'ibm-textcolor-purple-60' => 'Purple 60',
					'ibm-textcolor-red-30' => 'Red 30',
					'ibm-textcolor-red-40' => 'Red 40',
					'ibm-textcolor-red-50' => 'Red 50',
					'ibm-textcolor-red-60' => 'Red 60',
					'ibm-textcolor-teal-30' => 'Teal 30',
					'ibm-textcolor-teal-40' => 'Teal 40',
					'ibm-textcolor-teal-50' => 'Teal 50',
					'ibm-textcolor-teal-60' => 'Teal 60',
					'ibm-textcolor-yellow-10' => 'Yellow 10',
					'ibm-textcolor-yellow-30' => 'Yellow 30',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_565e71923fa31',
				'label' => __('Text align', $themeName),
				'name' => 'text_align',
				'type' => 'radio',
				'choices' => array (
					'default' => __('Default', $themeName),
					'center' => __('Center', $themeName)
				),
				'instructions' => __('How do you wish to have text aligned?', $themeName),
				'default_value' => 0,
			),
			array (
				'key' => 'field_565e71ba3fa32',
				'label' => __('Main Image', $themeName),
				'name' => 'main_image',
				'type' => 'image',
				'instructions' => __('Recommended resolution: 1440x320', $themeName),
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post',
					'operator' => '==',
					'value' => '61',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-field-group',
		'title' => __('Page Field Group', $themeName),
		'fields' => array (
			array (
				'key' => 'field_5660af591de4a',
				'label' => __('Display Title', $themeName),
				'name' => 'display_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574ef651c3do4',
				'label' => __('Title Size', $themeName),
				'name' => 'leadspace_title_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h1 ibm-large' => __('Larger', $themeName),
					'ibm-h1 ibm-medium' => __('Normal', $themeName),
					'ibm-h1' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h1 ibm-medium',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efbc84845h',
				'label' => __('Title Weight', $themeName),
				'name' => 'leadspace_title_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5660b0a0b61a8',
				'label' => __('Description', $themeName),
				'name' => 'description',
				'type' => 'text',
				'instructions' => __('This content will show up under the main title in the leadspace area', $themeName),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_574ef587c0927',
				'label' => __('Leadspace Text Color', $themeName),
				'name' => 'text_color',
				'type' => 'select',
				'instructions' => __('View https://www.ibm.com/standards/web/patterns/text for example color options', $themeName),
				'choices' => array (
					'ibm-textcolor-default' => 'Black',
					'ibm-textcolor-white-core' => 'White',
					'ibm-textcolor-blue-30' => 'Blue 30',
					'ibm-textcolor-blue-40' => 'Blue 40',
					'ibm-textcolor-blue-50' => 'Blue 50',
					'ibm-textcolor-blue-60' => 'Blue 60',
					'ibm-textcolor-gray-30' => 'Gray 30',
					'ibm-textcolor-gray-40' => 'Gray 40',
					'ibm-textcolor-gray-50' => 'Gray 50',
					'ibm-textcolor-gray-60' => 'Gray 60',
					'ibm-textcolor-gray-80' => 'Gray 80',
					'ibm-textcolor-green-30' => 'Green 30',
					'ibm-textcolor-green-40' => 'Green 40',
					'ibm-textcolor-green-50' => 'Green 50',
					'ibm-textcolor-green-60' => 'Green 60',
					'ibm-textcolor-magenta-20' => 'Magenta 20',
					'ibm-textcolor-magenta-30' => 'Magenta 30',
					'ibm-textcolor-magenta-50' => 'Magenta 50',
					'ibm-textcolor-magenta-60' => 'Magenta 60',
					'ibm-textcolor-orange-30' => 'Orange 30',
					'ibm-textcolor-orange-40' => 'Orange 40',
					'ibm-textcolor-orange-50' => 'Orange 50',
					'ibm-textcolor-orange-60' => 'Orange 60',
					'ibm-textcolor-purple-20' => 'Purple 20',
					'ibm-textcolor-purple-30' => 'Purple 30',
					'ibm-textcolor-purple-50' => 'Purple 50',
					'ibm-textcolor-purple-60' => 'Purple 60',
					'ibm-textcolor-red-30' => 'Red 30',
					'ibm-textcolor-red-40' => 'Red 40',
					'ibm-textcolor-red-50' => 'Red 50',
					'ibm-textcolor-red-60' => 'Red 60',
					'ibm-textcolor-teal-30' => 'Teal 30',
					'ibm-textcolor-teal-40' => 'Teal 40',
					'ibm-textcolor-teal-50' => 'Teal 50',
					'ibm-textcolor-teal-60' => 'Teal 60',
					'ibm-textcolor-yellow-10' => 'Yellow 10',
					'ibm-textcolor-yellow-30' => 'Yellow 30',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56e871ff9629b',
				'label' => __('Leadspace Image', $themeName),
				'name' => 'leadspace_image',
				'type' => 'image',
				'instructions' => __('Upload the article\'s main image. Size requirements 1440 × 320', $themeName),
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c3941354bea',
				'label' => __('Sidebar', $themeName),
				'name' => 'sidebar',
				'type' => 'true_false',
				'instructions' => __('(Does not work on Archive or Contributors pages)', $themeName),
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56b0ea5e44302',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => __('Enable Sidebar', $themeName),
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'top_level',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_sidebar',
		'title' => 'Sidebar',
		'fields' => array (
			array (
				'key' => 'field_56af820cc4069',
				'label' => __('Main Title', $themeName),
				'name' => 'main_title',
				'type' => 'text',
				'instructions' => __('Enter the title for the sidebar. Ex: \'Follow the conversation\'', $themeName),
				'required' => 1,
				'default_value' => __('Follow the conversation', $themeName),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56af82dac406a',
				'label' => __('Twitter Embed Code', $themeName),
				'name' => 'twitter_embed_code',
				'type' => 'wysiwyg',
				'instructions' => __('Follow code examples to create your own twitter timeline https://dev.twitter.com/web/embedded-timelines/user. If you have a twitter account already follow this link to timeline widget. https://twitter.com/settings/widgets', $themeName),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_56c3937cfe206',
				'label' => __('First Content Space', $themeName),
				'name' => 'first_cta_area',
				'type' => 'true_false',
				'message' => __('Enable First Content Space', $themeName),
				'default_value' => 0,
			),
			array (
				'key' => 'field_56af84c7b107d',
				'label' => __('First Section Title', $themeName),
				'name' => 'first_section_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c3937cfe206',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56afddf8b21ba',
				'label' => __('First Section Text Area', $themeName),
				'name' => 'first_section_text_area',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c3937cfe206',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56afde06b21bb',
				'label' => __('First Section CTA Text', $themeName),
				'name' => 'first_section_cta_text',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c3937cfe206',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56afde16b21bc',
				'label' => __('First Section CTA URL', $themeName),
				'name' => 'first_section_cta_url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c3937cfe206',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c393b9fe207',
				'label' => __('Second Content Space', $themeName),
				'name' => 'second_cta_area',
				'type' => 'true_false',
				'message' => __('Enable Second Content Space', $themeName),
				'default_value' => 0,
			),
			array (
				'key' => 'field_56afe59eb21bd',
				'label' => __('Second Section Title', $themeName),
				'name' => 'second_section_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c393b9fe207',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56afe5acb21be',
				'label' => __('Second Section Text Area', $themeName),
				'name' => 'second_section_text_area',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c393b9fe207',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56afe5c0b21bf',
				'label' => __('Second Section CTA Text', $themeName),
				'name' => 'second_section_cta_text',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c393b9fe207',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56afe5ccb21c0',
				'label' => __('Second Section CTA URL', $themeName),
				'name' => 'second_section_cta_url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56c393b9fe207',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_570d39524eadc',
				'label' => __('RSS Feed', $themeName),
				'name' => 'rss_feed',
				'type' => 'true_false',
				'instructions' => __('Adds fields for RSS Feed links', $themeName),
				'message' => __('Enable RSS Feed', $themeName),
				'default_value' => 0,
			),
			array (
				'key' => 'field_570fc8eae1aac',
				'label' => __('RSS Feed Section Title', $themeName),
				'name' => 'rss_feed_section_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_570d39524ead5',
				'label' => __('Page Feed', $themeName),
				'name' => 'page_feed',
				'type' => 'true_false',
				'instructions' => __('Select this option to add a feed for every page that contains the sidebar. If this is selected it will replace the first feed.', $themeName),
				'message' => '',
				'default_value' => 0,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_570d38d44eadb',
				'label' => __('RSS Feed 1 Link', $themeName),
				'name' => 'rss_feed_1_link',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570d39524ead5',
							'operator' => '!=',
							'value' => '1',
						),
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_570d3a497136d',
				'label' => __('RSS Feed 1 Title', $themeName),
				'name' => 'rss_feed_1_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570d39524ead5',
							'operator' => '!=',
							'value' => '1',
						),
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),

			array (
				'key' => 'field_570fc9757cf69',
				'label' => __('Add Second Feed?', $themeName),
				'name' => 'add_second_feed',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 0,
			),

						array (
				'key' => 'field_570d38d41094',
				'label' => __('RSS Feed 2 Link', $themeName),
				'name' => 'rss_feed_2_link',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570fc9757cf69',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_570d3a497976d',
				'label' => __('RSS Feed 2 Title', $themeName),
				'name' => 'rss_feed_2_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_570fc9757cf69',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_570d39524eadc',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post',
					'operator' => '==',
					'value' => '31822',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_tags-2',
		'title' => 'Tags',
		'fields' => array (
			array (
				'key' => 'field_56abc6de210fa',
				'label' => __('Main Image', $themeName),
				'name' => 'main_image',
				'type' => 'image',
				'instructions' => __('Image needs to be 1440 x 320', $themeName),
				'save_format' => 'object',
				'preview_size' => 'size-1440',
				'library' => 'all',
			),
			array (
				'key' => 'field_565e70b266d65',
				'label' => __('Post listing style', $themeName),
				'name' => 'post_listing_style',
				'instructions' => '',
				'type' => 'radio',
				'message' => '',
				'choices' => array(
					'grid' => __('Grid', $themeName),
					'stack' => __('Stack', $themeName),
					'global' => __('Follow global settings', $themeName),
				),
				'default_value' => 'global',
			),
			array (
				'key' => 'field_574ef651c3do6',
				'label' => __('Title Size', $themeName),
				'name' => 'leadspace_title_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h1 ibm-large' => __('Larger', $themeName),
					'ibm-h1 ibm-medium' => __('Normal', $themeName),
					'ibm-h1' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h1 ibm-medium',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574efbc84845i',
				'label' => __('Title Weight', $themeName),
				'name' => 'leadspace_title_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528efe56888f9',
				'label' => __('Description Size', $themeName),
				'name' => 'leadspace_description_size',
				'type' => 'select',
				'instructions' => __('Select size', $themeName),
				'choices' => array (
					'ibm-h3' => __('Larger', $themeName),
					'ibm-h4' => __('Normal', $themeName),
					'\'\'' => __('Smaller', $themeName),
				),
				'default_value' => 'ibm-h4',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528efe6d888fa',
				'label' => __('Description Weight', $themeName),
				'name' => 'leadspace_description_weight',
				'type' => 'select',
				'choices' => array (
					'ibm-bold' => __('Bold', $themeName),
					'\'\'' => __('Normal', $themeName),
					'ibm-light' => __('Thin', $themeName),
				),
				'default_value' => '\'\'',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_574qu587c3de8',
				'label' => __('Text Color', $themeName),
				'name' => 'text_color',
				'type' => 'select',
				'instructions' => __('View https://www.ibm.com/standards/web/patterns/text for example color options', $themeName),
				'choices' => array (
					'ibm-textcolor-default' => 'Black',
					'ibm-textcolor-white-core' => 'White',
					'ibm-textcolor-blue-30' => 'Blue 30',
					'ibm-textcolor-blue-40' => 'Blue 40',
					'ibm-textcolor-blue-50' => 'Blue 50',
					'ibm-textcolor-blue-60' => 'Blue 60',
					'ibm-textcolor-gray-30' => 'Gray 30',
					'ibm-textcolor-gray-40' => 'Gray 40',
					'ibm-textcolor-gray-50' => 'Gray 50',
					'ibm-textcolor-gray-60' => 'Gray 60',
					'ibm-textcolor-gray-80' => 'Gray 80',
					'ibm-textcolor-green-30' => 'Green 30',
					'ibm-textcolor-green-40' => 'Green 40',
					'ibm-textcolor-green-50' => 'Green 50',
					'ibm-textcolor-green-60' => 'Green 60',
					'ibm-textcolor-magenta-20' => 'Magenta 20',
					'ibm-textcolor-magenta-30' => 'Magenta 30',
					'ibm-textcolor-magenta-50' => 'Magenta 50',
					'ibm-textcolor-magenta-60' => 'Magenta 60',
					'ibm-textcolor-orange-30' => 'Orange 30',
					'ibm-textcolor-orange-40' => 'Orange 40',
					'ibm-textcolor-orange-50' => 'Orange 50',
					'ibm-textcolor-orange-60' => 'Orange 60',
					'ibm-textcolor-purple-20' => 'Purple 20',
					'ibm-textcolor-purple-30' => 'Purple 30',
					'ibm-textcolor-purple-50' => 'Purple 50',
					'ibm-textcolor-purple-60' => 'Purple 60',
					'ibm-textcolor-red-30' => 'Red 30',
					'ibm-textcolor-red-40' => 'Red 40',
					'ibm-textcolor-red-50' => 'Red 50',
					'ibm-textcolor-red-60' => 'Red 60',
					'ibm-textcolor-teal-30' => 'Teal 30',
					'ibm-textcolor-teal-40' => 'Teal 40',
					'ibm-textcolor-teal-50' => 'Teal 50',
					'ibm-textcolor-teal-60' => 'Teal 60',
					'ibm-textcolor-yellow-10' => 'Yellow 10',
					'ibm-textcolor-yellow-30' => 'Yellow 30',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'post_tag',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_v1-5',
		'title' => 'v1.5',
		'fields' => array (
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

?>