<?php

?>

<li><?php echo CMA_Settings::__('You can add "My Questions" and "My Answers" profile views per user anywhere on the site by using shortcodes:'); ?>
	<strong>[cma-my-questions]</strong>, <strong>[cma-my-answers]</strong>.
	<?php echo CMA_Settings::__('The AJAX support can be disabled by parameter ajax=0.'); ?>
</li>
<li><?php echo CMA_Settings::__('Generate questions list by using shortcode:'); ?>  <strong>[cma-questions]</strong>.
	<?php echo CMA_Settings::__('"Questions" and "My questions" recognize following additional parameters:'); ?>
	<a href="javascript:void(0)" onclick="jQuery(this).parent().find('ul').slideToggle()"><?php echo CMA_Settings::__('Show/Hide'); ?></a>
	<ul style="display:none;list-style-type:disc;margin-left:20px;">
	    <li><strong>limit</strong> - <?php echo CMA_Settings::__('number of questions/page to display (default: "Questions" 5 | "My questions" -1 [no limit])'); ?></li>
	    <li><strong>author</strong> - <?php echo CMA_Settings::__('ID of the question author (default: empty) [Question only]'); ?></li>
	    <li><strong>contributor</strong> - <?php echo CMA_Settings::__('ID of the question author or user who has answered for the question (default: empty) [Question only]'); ?></li>
	    <li><strong>cat</strong> - <?php echo CMA_Settings::__('slug of category (categories separate by commas) (default: empty)'); ?></li>
	    <li><strong>answered</strong> - <?php echo CMA_Settings::__('show only unanswered (0) or only answered (1) questions. Default: empty (all questions).'); ?></li>
	    <li><strong>resolved</strong> - <?php echo CMA_Settings::__('show only unresolved (0) or only resolved (1) questions. Default: empty (all questions).'); ?></li>
	    <li><strong>sort</strong> - <?php echo CMA_Settings::__('one of following: newest, hottest, views, votes (default: newest)'); ?></li>
	    <li><strong>form</strong> - <?php echo CMA_Settings::__('add "question form" (default: 0)'); ?></li>
	    <li><strong>formontop</strong> - <?php echo CMA_Settings::__('display the question form above the questions table (default: 0)'); ?></li>
	    <li><strong>dateposted</strong> - <?php echo CMA_Settings::__('display the thread posted date (default: 0)'); ?></li>
	    <li><strong>showcontent</strong> - <?php echo CMA_Settings::__('display the question\'s content below the title when showcontent=1 or fragment when showcontent=fragment (default: 0)'); ?></li>
	    <li><strong>search</strong> - <?php echo CMA_Settings::__('add "search form" above list (default: 1)'); ?></li>
	    <li><strong>pagination</strong> - <?php echo CMA_Settings::__('show pagination (default: 1)'); ?></li>
	    <li><strong>hidequestions</strong> - <?php echo CMA_Settings::__('hides the question list (default: 0)'); ?></li>
	    <li><strong>votes</strong> - <?php echo CMA_Settings::__('show the number of votes (default: 1)'); ?></li>
	    <li><strong>views</strong> - <?php echo CMA_Settings::__('show the number of views (default: 1)'); ?></li>
	    <li><strong>answers</strong> - <?php echo CMA_Settings::__('show the number of answers (default: 1)'); ?></li>
	    <li><strong>updated</strong> - <?php echo CMA_Settings::__('show the information about question\'s last update (default: 1)'); ?></li>
	    <li><strong>authorinfo</strong> - <?php echo CMA_Settings::__('show the infformation about question\'s author (default: 1)'); ?></li>
	    <li><strong>statusinfo</strong> - <?php echo CMA_Settings::__('show the information about question\'s status (default: 0)'); ?></li>
	    <li><strong>tags</strong> - <?php echo CMA_Settings::__('show questions\' tags (default: 1)'); ?></li>
	    <li><strong>navbar</strong> - <?php echo CMA_Settings::__('show the full navigation bar (default: 0)'); ?></li>
	    <li><strong>subtree</strong> - <?php echo CMA_Settings::__('limit the categories filter options only to subcategories of the current category given by the cat parameter (default: 0)'); ?></li>
	    <li><strong>displaycategories</strong> - <?php echo CMA_Settings::__('display category name next to the question (default: 0)'); ?></li>
	    <li><strong>ajax</strong> - <?php echo CMA_Settings::__('enable or disable AJAX support (default: 1)'); ?></li>
	    <li><strong>sortbar</strong> - <?php echo CMA_Settings::__('show the sorting bar (default: 0)'); ?></li>
	    <li><?php echo CMA_Settings::__('Example'); ?>: <strong>[cma-questions limit="10" author="123" sort="hottest" form="1"]</strong></li>
	</ul></li>
<li><?php echo CMA_Settings::__('You can add the Categories table anywhere on the site by using shortcode:'); ?> <strong>[cma-categories questions=1 answers=1 follow=1 header=1 unanswered=1 parent=category experts=0]</strong> or <strong>[cma-categories-list]</strong></li>
<li><?php echo CMA_Settings::__('User\'s followed threads and categories:'); ?> <strong>[cma-followed]</strong></li>
<li><?php echo CMA_Settings::__('Question form:'); ?> <strong>[cma-question-form cat=optionalCategory title=0 backlink=1]</strong></li>
<li><?php echo CMA_Settings::__('Questions index similar like on the Answers main page:'); ?> <strong>[cma-index]</strong> - <?php
	echo CMA_Settings::__('Notice: this shortcode is the same as cma-questions and accepts the same parameters. Only difference are the default parameters values.'); ?></li>
<li><?php echo CMA_Settings::__('To attach a YouTube or Vimeo clip to the thread just put the URL in brackets:'); ?> [https://youtu.be/Zkdf3kaso]</li>
<li><strong><?php echo CMA_Settings::__('Notice: shortcodes are case-sensitive.'); ?></strong></li>
