<?php

require_once ABSPATH . 'wp-includes/class-wp-editor.php';

$populatedData = CMA_BaseController::getPopulatedData();
$additionalFormClass = (!CMA_Settings::getOption(CMA_Settings::OPTION_MARKUP_BOX)) ? 'no-markup-box' : '';
$queriedObject = CMA_AnswerController::$query->get_queried_object();
$selectCategoryId = (isset($queriedObject->term_id) ? $queriedObject->term_id : (!empty($populatedData['thread_category']) ? $populatedData['thread_category'] : null));
$tiny = isset($tiny) ? $tiny : FALSE;
$catId = isset($catId) ? $catId : NULL;
$isAjax = CMA_BaseController::isAjax();
$threadId = isset($populatedData['thread_id']) ? $populatedData['thread_id'] : null;
if (!isset($thread)) $thread = null;
if (empty($displayOptions['formtags']) AND !empty($_GET['formtags'])) {
	$displayOptions['formtags'] = $_GET['formtags'];
}
if (empty($populatedData['thread_tags']) AND !empty($displayOptions['formtags'])) {
	$populatedData['thread_tags'] = $displayOptions['formtags'];
}
$showRichTextEditor = (CMA_Settings::getOption(CMA_Settings::OPTION_RICHTEXT_EDITOR)); // AND !CMA_AJAX);


// include '/home/robert/Pobrane/cat-nav.php';

?>
<div class="cma-form-container cma-question-form-container <?php echo esc_attr($additionalFormClass); ?>">

	<?php if (!empty($edit) AND !$isAjax OR !empty($displayOptions['showBacklink'])): ?>
		<a class="cma-backlink" href="<?php echo esc_attr(CMA::getReferer()); ?>"> &laquo; <?php echo CMA_Labels::getLocalized('back_to_previous_page'); ?></a>
	<?php endif; ?>

    <?php if( CMA_Thread::canPostQuestions() ): ?>
        <form action="<?php echo esc_attr(empty($edit) ? get_post_type_archive_link(CMA_Thread::POST_TYPE) : $_SERVER['REQUEST_URI']);
        	?>"  method="post" class="cma-thread-add" id="cma-thread-add" enctype="multipart/form-data">

        	<!--
        	<ul class="cma-categories-tabs"><?php

// 			$categories = CMA_Category::getCategories();
// 			foreach ($categories as $id => $categoryName) {
// 				$selected = (($selectCategoryId ? $selectCategoryId : $catId) == $id);
// 				printf('<li data-id="%d" class="%s">%s</li>', $id, ($selected ? 'current' : ''), $categoryName);
// 			}

			?></ul>
			<script>
			jQuery(function($) {
				var select = $('.cma-question-form-container select[name=thread_category]');
				select.replaceWith($('<input/>', {type: 'hidden', name: select.attr('name'), value: select.val()}));
				$('.cma-categories-tabs li').click(function() {
					var btn = $(this);
					var input = btn.parents('.cma-question-form-container').find('*[name=thread_category]');
					input.val(btn.data('id'));
					btn.parents('ul').first().find('li').removeClass('current');
					btn.addClass('current');
				});
				if ($('.cma-categories-tabs li.current').length == 0) {
					$('.cma-categories-tabs li').first().click();
				}
			});
			</script>
			<style>
			.cma-form-choose-category {display: none;}
			.cma-categories-tabs {margin: 2em 0 0 0 !important; padding: 0 !important;}
			.cma-categories-tabs, .cma-categories-tabs li {list-style: none;}
			.cma-categories-tabs li {display: inline-block; margin: 0 3px 0 0 !important; padding: 0.5em 1em !important; background: #eeeeee; color: #666666; cursor: pointer; border: 1px solid #dddddd; position: relative; top: 2px;}
			.cma-categories-tabs li.current, .cma-categories-tabs li:hover {background: white; color: black; border-bottom-style: none; border-color: #cccccc;}
			.cma-question-form-container .cma-form-inner {border: solid 1px #cccccc; padding: 10px;}
			</style>

			-->

			<div class="cma-form-inner">

            <input type="hidden" name="cma-action" value="<?php echo (empty($edit) ? 'add' : 'edit'); ?>" />
            <input type="hidden" name="cma-referrer" value="<?php echo esc_attr($_SERVER['REQUEST_URI']); ?>" />
            <input type="hidden" name="nonce" value="<?php echo esc_attr(wp_create_nonce('cma_question')); ?>"/>
            <?php if (!empty($redirectAfterPost)): ?>
            	<input type="hidden" name="cma-redirect" value="<?php echo esc_attr($redirectAfterPost); ?>" />
            <?php endif; ?>

			<?php if (empty($displayOptions['hideTitle'])): ?>
            	<h3><?php echo (empty($edit) ? CMA_Labels::getLocalized('ask_a_question') : CMA_Labels::getLocalized('edit_your_question')); ?></h3>
            <?php endif; ?>

            <div class="cma-form-input">
                <input type="text" size="50" name="thread_title" required placeholder="<?php
                	echo esc_attr(CMA_Labels::getLocalized('enter_question_title'));
                	?>" value="<?php if( isset($populatedData['thread_title']) ) echo esc_attr($populatedData['thread_title']);
                	?>" data-limitify="<?php echo CMA_Settings::getOption(CMA_Settings::OPTION_JS_LIMIT_QUESTION_TITLE) ?>" />
            </div>

            <?php if( !$tiny && CMA_Settings::getOption(CMA_Settings::OPTION_MARKUP_BOX) ): ?>
                <ul class="cma-form-notes">
                    <li><?php _e('Allow markup', 'cm-answers-pro'); ?>: &lt;strong&gt;, &lt;em&gt;, &lt;a&gt;</li>
                    <li><?php _e('Wrap your code using', 'cm-answers-pro'); ?> &lt;pre&gt;&lt;/pre&gt;</li>
                </ul>
            <?php endif; ?>

            <div class="cma-form-input">
                <?php
                $questionEditorContent = '';
                if( isset($populatedData['thread_content']) )
                {
                    $questionEditorContent = ($showRichTextEditor ?
						$populatedData['thread_content'] :
						stripslashes(esc_html($populatedData['thread_content']))
					);
                }

                if ($showRichTextEditor)
                {
                	remove_filter ('the_content',  'wpautop');
                    wp_editor($questionEditorContent, 'question-content-form', array(
                    	'textarea_name' => 'thread_content',
						'textarea_rows' => CMA_Settings::getOption(CMA_Settings::OPTION_EDITOR_ROWS),
                    ));
                }
                else
                {

                    if( CMA_Settings::getOption(CMA_Settings::OPTION_QUESTION_DESCRIPTION_OPTIONAL) )
                    {
                        $placeholder = CMA_Labels::getLocalized('enter_question_content_optional');
                    } else {
						$placeholder = CMA_Labels::getLocalized('enter_question_content');
					}
                    ?>
                    <textarea class="cma-form-content" name="thread_content" cols="50" rows="<?php
                    	echo CMA_Settings::getOption(CMA_Settings::OPTION_EDITOR_ROWS); ?>" id="question-content-form-<?php echo rand(1, 999999);
                    	?>" data-limitify="<?php
                    	echo CMA_Settings::getOption(CMA_Settings::OPTION_JS_LIMIT_QUESTION_DESCRIPTION); ?>" placeholder="<?php
                    	echo esc_attr($placeholder); ?>" data-tinymce="<?php
                		echo intval(CMA_Settings::getOption(CMA_Settings::OPTION_RICHTEXT_EDITOR)/* AND CMA_AJAX*/); ?>"><?php
                    	echo esc_html($questionEditorContent); ?></textarea>
                    <?php
                }
                ?>
                <p class="cma-attach-video-tip"><?php echo CMA::__('Attach YouTube/Vimeo clip putting the URL in brackets:'); ?> [https://youtu.be/Zkdf3kaso]</p>
            </div>

            <?php if (CMA_Settings::getOption(CMA_Settings::OPTION_USER_RELATED_QUESTIONS_ENABLE)): ?>
	            <div class="cma-form-input"><?php echo CMA_Labels::getLocalized('user_related_questions_input_label'); ?>
	            	<textarea name="cma_related_questions" rows="3" placeholder="<?php
	            		echo esc_attr(CMA_Labels::getLocalized('user_related_questions_input_placeholder')); ?>"></textarea>
	            </div>
            <?php endif; ?>

            <?php do_action('cma_question_form_after_textarea', $thread, $populatedData); ?>

            <?php if( CMA_Settings::getOption(CMA_Settings::OPTION_TAGS_SWITCH) ) : ?>
                <?php do_action('CMA_form_tags', (isset($populatedData['thread_tags']) ? $populatedData['thread_tags'] : '')); ?>
            <?php endif; ?>

            <?php if (empty($edit)): ?>

	            <?php
	            if ( $catId ):
	                echo '<input type="hidden" name="thread_category" value="' . $catId . '" />';
	            else:

	            	echo '<div class="cma-form-input cma-form-choose-category"><label>';
	            	if ($label = CMA_Labels::getLocalized('choose_category_label')) {
						echo $label .':<br />';
					}

	            	$isCategoryRequired = CMA_Settings::getOption(CMA_Settings::OPTION_QUESTION_REQUIRE_CATEGORY);
	            	switch (CMA_Settings::getOption(CMA_Settings::OPTION_CATEGORY_FILTER_MODE)):

	            		case CMA_Settings::CATEGORY_FILTER_MODE_TWO_LEVEL:
	            			$categories = CMA_Category::getRootCategories();
	            			?><select name="thread_category" class="cma-filter-category-primary"<?php
	            				if ($isCategoryRequired) echo ' required'; ?>>
            					<option value=""><?php echo esc_html(CMA_Labels::getLocalized('choose_category')); ?></option><?php
            					foreach ($categories as $category_id => $categoryName):
            						$selected = (isset($selectCategoryId)
            							AND ($category_id == $selectCategoryId
            								OR $category_id == wp_get_term_taxonomy_parent_id($selectCategoryId, CMA_Category::TAXONOMY)));
            						?><option value="<?php echo esc_attr($category_id); ?>" data-url="<?php echo esc_attr(get_term_link($category_id, CMA_Category::TAXONOMY));
            						?>"<?php if ($selected) echo ' selected="selected"';
            						?>><?php echo esc_html($categoryName); ?></option><?php
            					endforeach;
            				?></select>
            				<select name="thread_subcategory" class="cma-filter-category-secondary"><?php
            					$parentCategoryId = wp_get_term_taxonomy_parent_id($selectCategoryId, CMA_Category::TAXONOMY);
            					if (!empty($selectCategoryId)):
            						if (!CMA_Settings::getOption(CMA_Settings::OPTION_ALLOW_POST_ONLY_SUBCATEGORIES)): ?>
										<option value="0"><?php echo CMA_Labels::getLocalized('all_subcategories') ?></option>
									<?php endif;
            						$subcategories = CMA_Category::getSubcategories(empty($parentCategoryId) ? $selectCategoryId : $parentCategoryId);
            						foreach ($subcategories as $category_id => $categoryName):
            							$selected = ($category_id == $selectCategoryId);
            							?><option value="<?php echo esc_attr($category_id); ?>"<?php if ($selected) echo ' selected="selected"';
            							?>><?php echo esc_html($categoryName); ?></option><?php
            						endforeach;
            					endif;
            				?></select><?php
            			break;

            			case CMA_Settings::CATEGORY_FILTER_MODE_TREE:
            			default:

			                $categories = CMA_Category::getCategoriesTree();
			                if( $categories ): ?>
		                        <select name="thread_category"<?php if ($isCategoryRequired) echo ' required'; ?>>
		                            <option value=""><?php echo CMA_Labels::getLocalized('choose_category'); ?></option>
		                            <?php foreach($categories as $key => $val):
		                                $selected = ( (!isset($populatedData['thread_category']) && ( isset($queriedObject->term_id) && $queriedObject->term_id == $key ))
											|| isset($populatedData['thread_category']) && $populatedData['thread_category'] == $key ) ?
												' selected="selected"' : '';
		                                ?><option value="<?php echo esc_attr($key); ?>" <?php echo $selected; ?>><?php echo esc_html($val); ?></option>
		                            <?php endforeach; ?>
		                        </select>
			                    <?php
			                endif;

	                endswitch;

	                echo '</label></div>';

	            endif;


	        endif; ?>

            <div class="cma-category-custom-fields"><?php
	            if (!empty($selectCategoryId) OR !empty($catId)):
					do_action('cma_question_form_category_custom_fields', ($selectCategoryId ? $selectCategoryId : $catId), $threadId);
				endif;
			?></div>

			<?php do_action('cma_question_form_after_category', $thread, $populatedData); ?>

			<?php if (empty($edit)): ?>
				<?php do_action('CMA_display_question_form_upload'); ?>
	            <div class="cma-form-options">
	            	<?php if(CMA_Thread::canDisplayNotifyCheckbox()): ?>
		                <label class="cma-form-option-label">
		                    <input name="thread_notify" type="checkbox" value="1" <?php
		                    if( isset($populatedData['thread_notify']) OR CMA_Settings::getOption(CMA_Settings::OPTION_NOTIFY_CHECKBOX_CHECKED) )
		                    	echo 'checked="checked"'; ?>/>
		                    <?php echo CMA_Labels::getLocalized('notify_me_of_follow'); ?>
		                </label>
		            <?php endif; ?>
	            </div>
	            <?php if (CMA_Settings::getOption(CMA_Settings::OPTION_ANONYMOUS_USER_ENABLE) AND is_user_logged_in()): ?>
	            	<div class="cma-form-options">
		                <label class="cma-form-option-label cma-thread-nickname-field">
		                	<?php echo CMA_Labels::getLocalized('anonymous_nickname_field'); ?>
		                	<input type="text" name="anonymous_nickname" value="<?php echo esc_attr(isset($populatedData['anonymous_nickname']) ? $populatedData['anonymous_nickname'] : ''); ?>" />
		                </label>
	            	</div>
	            <?php endif; ?>

            <?php endif; ?>

            <?php do_action('cma_frontend_question_form_body_after'); ?>

            <input type="submit" class="ibm-btn-pri ibm-btn-blue-50" value="<?php echo esc_attr(CMA_Labels::getLocalized(empty($edit) ? 'button_add_question' : 'button_edit_question')); ?>" />

            <?php do_action('cma_frontend_question_form_bottom'); ?>

        </div></form>
    <?php endif; ?>
    <?php if (!is_user_logged_in() ) do_action('CMA_login_form'); ?>

</div>

<script type="text/javascript">
jQuery(function($) {
	// CMA_tags_init($);
});
</script>
<?php if ($showRichTextEditor AND CMA_AJAX) \_WP_Editors::editor_js(); ?>
